services:

  service_a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_a
    networks:
      our-network:
    ports:
      - "17500:4444"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1.5G
    command: ["python3", "/app/container_a/app.py"]  # Override CMD for service_a

  service_b:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_b
    networks:
      our-network:
    ports:
      - "18500:8888"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1.5G
    command: ["python3", "/app/container_b/app.py"]  # Override CMD for service_b

networks:
  our-network:
    driver: bridge
